### ISSUE TITLE
Calculate final contribution rewards per address

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-crowdloan-ui#14]
**BSX:**
✅  matching # of contributions & sum of all contributions (total KSM raised) with external source e.g. subscan
✅ bsxMultiplier is 1 for everyone, since we've overflown to the 8th auction and all the new contributions from auction 8, were within the first two days - we've reached the cap then
✅ totalContributionWeight should === total ksm raised, since the bsx multiplier is 1
🚫 precision loss for BSX reward calculation is the following 14999999999.99999986499981251114,  we can either divide this remained by the amount of contributions and equally distribute this to all contributors, or do something else with it (-> treasury, -> burn, whatever) TODO: calculate current USD value of the lost precision, it'll be quite negligible
🚫  TODO:  fix UI's bsxMultiplier calculation, for now just hardcode return 1

**HDX:**
🚫 TODO: set KSM/USD price for the hdx reward calculation (this will change the total HDX distributed if the KSM price goes up compared to the 400$ we're using now)
🚫 TODO: double check if opporunity ccost is 13.75%
✅ HDX bonus went from 0.3 (before auction #8) to 0.05 (from auction #8) (we fixed a bug at auction #7 end block  (9233727)where the lead percentage rate was wrongly calculated - there was one contribution at that time)
🚫 TODO: fix ^^ on UI
✅ Total HDX reward: 40238028.501822136742

**Communications**
TODO: update basilisk_rewards.md (https://gist.github.com/maht0rz/d7858f383ee16a912b5b8e32c5b3f698) with latest info, create a separate gist with output from the final calculations.

**Comment by enthusiastmartin** [comment]
Rewards

https://gist.github.com/maht0rz/d9cb7d2b28e6fe8e0d4dadde6d265929

**Comment by maht0rz** [comment]
This issue was partially resolved in PR #15, UI update is still TBD.

**Comment by maht0rz** [comment]
API used for dynamic KSM price: [Coingecko](https://api.coingecko.com/api/v3/coins/kusama/market_chart?vs_currency=usd&days=89)

**Comment by timothydm42** [comment]
@maht0rz @enthusiastmartin 

The [rewards.json](https://raw.githubusercontent.com/galacticcouncil/Basilisk-crowdloan-ui/main/scripts/data/rewards.json) takes a price from ~2hrs _before_ the contribution happened,  instead of the price that is closest-and-before the contribution happend:

Here is the first element in the `rewards` array in the `rewards.json` file: 
- ![image](https://user-images.githubusercontent.com/25761350/142469776-aed1b73d-b039-4fa1-9659-2a2fe78661f2.png)

-  `createdAt` 👆  to unix timestamp for comparison 👇  : ![image](https://user-images.githubusercontent.com/25761350/142472060-8a3f51da-bfa8-4cd2-8f83-3b5880444c18.png)


- Here is the output from the [KSM price API](https://api.coingecko.com/api/v3/coins/kusama/market_chart?vs_currency=usd&days=89) ‼️ it only gives us the price every _hour_ ‼️ 
![image](https://user-images.githubusercontent.com/25761350/142472606-6d159200-3d56-44fa-8d5d-2b671eeb2b87.png)

- so you see,  if we want to use the price that is closest-to-and-before the contribution,  then we want to use the highlighted timestamp's price.  
  - In this case it's a $20 difference.  ( `378` from `rewards.json`  vs.  `391` as the closest-to-and-before price )
  - It is much smaller in most other cases.

I verified this with three other contributions at different times.

So we have some questions:

what do we care about here/what will our tribesmates expect/want us to do ? 

-  is hourly price acceptable ?  ( so far Martin and I have not found more precise data _easily_ available )
-  Get the price that is before-and-closest to contribution ?
-  Get the mean between the price before and after the contribution ?
-  not worry about it 🤷‍♀️ 
-  something else 🙂 ?

**Comment by mrq1911** [comment]
HDX rewards should be checked again and then tripled as these rewards will be distributed after the migration to parachain
