### ISSUE TITLE
Create script to generate batch transactions for vesting of BSX crowdloan rewards

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-crowdloan-ui#23]
- [x] parse https://github.com/galacticcouncil/Basilisk-crowdloan-ui/blob/develop/scripts/data/rewards.json
- [x] generate batch call
- [x] test run

**Comment by maht0rz** [comment]
The way this should be handled with the current vesting palette is that we'll set up two independent vesting schedules:

1st vesting schedule will unlock 30% of the rewards at the block when the LBP ends. 

2nd vesting schedule will vest 70% of the remaining rewards for the user from (parachain)slotStart to slotEnd.

`vesting.claim()` is disabled until the LBP ends in the runtime, as a side-effect, this will mean that once you call claim after the LBP is done you'll unlock the initial 30% + a portion of the 2nd vesting schedule at once.

1st vesting schedule can be a single large period, since it's meant to be claimed only once all together.

**Comment by mrq1911** [comment]
from what account will be tokens actually vested? currently, we are only alloving to be the sudo or treasury account

**Comment by timbo-timboa** [comment]
Welp,  we did this... anything we should do here before we close @lumir-mrkva @jak-pan @maht0rz ?
